angular
  .module('app',
    ['ui.router',
      'ngMaterial',
      'md.data.table',
      'ngResource',
      'ngMessages',
      'ncy-angular-breadcrumb',
      'ui-notification',
      'sticky',
      'angularMoment',
      'moment-picker',
      'ngStorage'
    ]);
